{% set name = "qasync" %}
{% set version = "0.28.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/CabbageDevelopment/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 1b80e2315663350b04c2c780d8ea0c76f5e4cf09fb55347e40cb16540e6411d7

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv
  skip: True  # [py<38]

requirements:
  host:
    - python
    - pip
    - uv-build >=0.8.3,<0.9.0
  run:
    - python
    - h11 >=0.16.0,<1.0

test:
  source_files:
    - tests
  imports:
    - qasync
  commands:
    - pip check
    - pytest -v tests  # [not linux]
    # Aborted" when trying to initialize QApplication in a session-scoped fixture on Linux,
    # which indicates Qt is attempting to create GUI resources without a display server (X11/Wayland) being available in the CI environment.
    # Configure the test environment to run in headless mode using xvfb:
    - xvfb-run -a pytest -v tests  # [linux]
  requires:
    - pip
    - pytest >=8.4
    - pyqt
    - xvfb-run-linux  # [linux]

about:
  home: https://github.com/CabbageDevelopment/qasync
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Implementation of the PEP 3156 Event-Loop with Qt.
  description: |
    qasync allows coroutines to be used in PyQt/PySide applications by
    providing an implementation of the PEP 3156 event-loop.
  dev_url: https://github.com/CabbageDevelopment/qasync
  doc_url: https://github.com/CabbageDevelopment/qasync

extra:
  recipe-maintainers:
    - ales-erjavec
