{% set name = "qasync" %}
{% set version = "0.27.1" %}

# on our builders there is no X11 installed and therefore import
# test will fail
{% if target_platform != "linux-aarch64" and target_platform != "linux-64"%}
{% set enable_testingui = true %}
{% else %}
{% set enable_testingui = false %}
{% endif %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8dc768fd1ee5de1044c7c305eccf2d39d24d87803ea71189d4024fb475f4985f

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv
  skip: True  # [py<38 or (linux and s390x)]

requirements:
  host:
    - python
    - pip
    - poetry-core >=1.5.0
  run:
    - python

{% if enable_testingui %}
test:
  imports:
    - qasync
  requires:
    - pyqt
    - pip
  commands:
    - pip check
{% endif %}

about:
  home: https://github.com/CabbageDevelopment/qasync
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Implementation of the PEP 3156 Event-Loop with Qt.
  description: |
    qasync allows coroutines to be used in PyQt/PySide applications by
    providing an implementation of the PEP 3156 event-loop.
  dev_url: https://github.com/CabbageDevelopment/qasync
  doc_url: https://github.com/CabbageDevelopment/qasync

extra:
  recipe-maintainers:
    - ales-erjavec
